name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup build
      uses: ./.github/actions/setup-build
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest -PplayerKey=${{ secrets.PLAYER_KEY }}
    - name: Display unit test results
      id: test-results
      uses: bitmovin-engineering/action-junit-report@v4
      if: always()
      with:
        check_name: 'Unit tests: Results'
        report_paths: '**/build/test-results/testDebugUnitTest/TEST-*.xml'
