name: Publish SDK

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Publish Nielsen Mediametrie SDK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup build
        uses: ./.github/actions/setup-build

      - name: Build release AAR
        run: ./gradlew :nielsen-mediametrie-sdk:clean :nielsen-mediametrie-sdk:assembleRelease

      - name: Publish to Maven repository
        run: |
          ./gradlew :nielsen-mediametrie-sdk:publish \
            -PmavenUsername=${{ secrets.MAVEN_USERNAME }} \
            -PmavenPassword=${{ secrets.MAVEN_PASSWORD }}
